import {
  describe,
  expect,
  it,
} from "vitest";

import {
  MATCH_SESSION_ID_PREFIX,
  createMatchSessionId,
  isMatchSessionId,
} from "../src/matchSessionId.js";

describe("match session ID", () => {
  it("uses the versioned session ID prefix", () => {
    expect(
      MATCH_SESSION_ID_PREFIX,
    ).toBe("ms1_");
  });

  it("creates a valid session ID", () => {
    const sessionId =
      createMatchSessionId();

    expect(sessionId).toMatch(
      /^ms1_[0-9a-f]{32}$/,
    );

    expect(
      isMatchSessionId(
        sessionId,
      ),
    ).toBe(true);
  });

  it("creates different session IDs", () => {
    const first =
      createMatchSessionId();

    const second =
      createMatchSessionId();

    expect(first).not.toBe(
      second,
    );
  });

  it("supports a deterministic random source for tests", () => {
    const sessionId =
      createMatchSessionId(
        (bytes) => {
          bytes.fill(0xab);

          return bytes;
        },
      );

    expect(sessionId).toBe(
      "ms1_abababababababababababababababab",
    );
  });

  it("converts every generated byte to two hexadecimal characters", () => {
    const sessionId =
      createMatchSessionId(
        (bytes) => {
          for (
            let index = 0;
            index < bytes.length;
            index += 1
          ) {
            bytes[index] =
              index;
          }

          return bytes;
        },
      );

    expect(sessionId).toBe(
      "ms1_000102030405060708090a0b0c0d0e0f",
    );
  });

  it("rejects a random source returning the wrong byte length", () => {
    expect(() =>
      createMatchSessionId(
        () =>
          new Uint8Array(
            new ArrayBuffer(15),
          ),
      ),
    ).toThrow(
      "Match session random source must return exactly 16 bytes",
    );
  });

  it("rejects malformed session IDs", () => {
    expect(
      isMatchSessionId(
        "ms1_invalid",
      ),
    ).toBe(false);

    expect(
      isMatchSessionId(
        "ms1_0123456789abcdef",
      ),
    ).toBe(false);

    expect(
      isMatchSessionId(
        "ms2_0123456789abcdef0123456789abcdef",
      ),
    ).toBe(false);

    expect(
      isMatchSessionId(
        "rp1_0123456789abcdef0123456789abcdef",
      ),
    ).toBe(false);

    expect(
      isMatchSessionId(
        "ms1_0123456789ABCDEF0123456789ABCDEF",
      ),
    ).toBe(false);

    expect(
      isMatchSessionId(null),
    ).toBe(false);
  });
});